# Generated by Django 2.2.4 on 2020-03-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_testuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testuser',
        ),
    ]
